dictionary = {
    "agents": [
        {
            "name": "thief",
            "persona": "I am a thief that lives near the village. I pickpocket villagers and loot their homes when while they are away. I hate to fight and I am very fast to flee from danger.",
        },
        {
            "name": "person",
            "persona": "I am very hungry and very sick. I ended up homeless because I refused to do what my family wanted and was disowned. I look for scraps to feed my empty belly, while others look down on me.",
        },
    ],
    "setting": {
        "name": "Port Tavern",
        "category": "Port",
        "description": "The port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.",
        "background": "The port tavern used to be a private domicile. It belonged to a wealthy merchant who lived there with his beautiful wife and daughters. This merchant was intelligent, charming, well-respected, and was addicted to gambling. Luck had been on his side for his entire life, until one night when he was playing cards against local merchants. Out of cash and overconfident, he bet his house to a small, round man with a bushy mustache and a questionable past.",
    },
    "character": (
        "thief",
        "person",
        "thief",
        "person",
        "thief",
        "person",
        "thief",
        "person",
        "thief",
        "person",
        "thief",
        "person",
        "thief",
        "person",
    ),
    "context": (
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA person is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA thief is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA person is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA thief is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA person is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA thief is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA person is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA thief is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA person is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA thief is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA person is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA thief is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA person is here. You are carrying nothing. ",
        "You are in the Port Tavern.\nThe port tavern is the shadiest of all the shady bars in the city. Every night, on its grimy stools at the wooden bar, you can find some of the slimiest sailors in the world. The walls are of peeling blue paint and are always dripping with condensation. Women of ill-repute line one wall, old men on the verge of passing out line another. The floor is littered with trash, barnacles, and bodily fluids. Tending the bar is a small, round man with a bushy mustache.\nThere's a wooden bar, two stools, a fluid, and a barnacle here.\nA thief is here. You are carrying nothing. ",
    ),
    "room_objects": (
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
        ["a fluid", "a stool", "a wooden bar", "a barnacle", "a stool"],
    ),
    "room_agents": (
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
        ["a person", "a thief"],
    ),
    "all_descriptions": {
        "a fluid": "Bodily fluids created a viscous sheen on the floor where the incident occurred.",
        "a stool": "This stool is old and dusty and has a broken leg",
        "a wooden bar": "The bar is old, but still has plenty life left in it. Passed down through generations, it's surface is adorned in scratches, knife marks, and name carvings that add a sense of beauty and immeasurable value to the aging piece.",
        "a barnacle": "Upon further investigation of the barnacles, they appear to be brown, hard and wet from the sea.",
    },
    "available_actions": (
        ["hit person", "get barnacle", "hug person", "get stool"],
        ["hit thief", "hug thief", "get barnacle", "get stool"],
        ["hit person", "get barnacle", "hug person", "get stool"],
        ["hit thief", "hug thief", "get barnacle", "get stool"],
        ["hit person", "get barnacle", "hug person", "get stool"],
        ["hit thief", "hug thief", "get barnacle", "get stool"],
        ["hit person", "get barnacle", "hug person", "get stool"],
        ["hit thief", "hug thief", "get barnacle", "get stool"],
        ["hit person", "get barnacle", "hug person", "get stool"],
        ["hit thief", "hug thief", "get barnacle", "get stool"],
        ["hit person", "get barnacle", "hug person", "get stool"],
        ["hit thief", "hug thief", "get barnacle", "get stool"],
        ["hit person", "get barnacle", "hug person", "get stool"],
        ["hit thief", "hug thief", "get barnacle", "get stool"],
    ),
    "carrying": ([], [], [], [], [], [], [], [], [], [], [], [], [], []),
    "wearing": ([], [], [], [], [], [], [], [], [], [], [], [], [], []),
    "wielding": ([], [], [], [], [], [], [], [], [], [], [], [], [], []),
    "speech": (
        "Hey, you orc, get out of here.",
        "I'm no orc. I'm just a homeless man",
        "I'm sorry, I thought you were someone else. Can I buy you a beer?",
        "That would be so kind. I am so hungry and have been feeling sick.",
        "Oh, I don't have enough money to do that. Sorry, I need to leave.",
        "I should have known even a thief would look down on me.",
        "I have to go.",
        "What's that in your pocket?",
        "It's a book I like to read sometimes.",
        "Who did you steal it from?",
        "I didn't steal it from anyone. Listen, I don't want a fight.",
        "Neither do I. I'm just desperate for a bite to eat.",
        "Sorry.",
        "Where are you going?",
    ),
    "emote": (
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        "shrug",
        None,
    ),
    "action": (
        None,
        None,
        None,
        "hug thief",
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),
}
